### PR TITLE
Fix UI bugs for FindCommand

### LINKED ISSUE #133: Bug where note being updated does not update the note UI
Currently if a note is being displayed, and the users uses the `addnote` command to edit the note, the note display will not change. This is probably not ideal.

The simplest way to fix this would be to edit the `addnote` command to also update the note being showed if the author of the note is the note being edited, but this seems a bit brittle.

A better way to fix this would be to make the UI "watch" the actual Note object, so that whenever it's been modified the Note display will change. Similar to how editing a person causes the person's displayed field to change.

### PR DESCRIPTION
**Pull request by jiahui0309**
Closes #133.

This PR covers:
- Implemented tracking of the `Person` whose note is displayed on the panel.
- Modified the `addnote` command to check if the note being added belongs to the tracked `Person`.

Concerns:
- Used a variable to track the `Person` in `find` command, and used `get` to retrieve the `Person` in `addnote` command
  - Not sure if this violates any rule (Single Responsibility Principle?)
 
Result after running `find s1234567b`:
 Screenshot 2024-03-29 at 3 22 23 PM
From the previous screen, running `addnote s1234567b n/Covid` will show the screen below:
Screenshot 2024-03-29 at 3 23 28 PM

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -20,6 +21,8 @@ public class FindCommand extends Command {
             + "Parameters: IC (must be a valid identity card number) \n"
             + "Example: " + COMMAND_WORD + " t1234567A";
 
+    private static Person foundPerson = null;
```
Comment (drustanyjt) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:24]: @jiahui0309 I think ur right that this is violating some design principles. It'll also mean that if we add a new command (like `show`) then the `foundPerson` variable would need to be invalidated.

Comment (drustanyjt) [inline src/main/java/seedu/address/logic/commands/FindCommand.java]: @jiahui0309 I think ur right that this is violating some design principles. It'll also mean that if we add a new command (like `show`) then the `foundPerson` variable would need to be invalidated.

File: src/main/java/seedu/address/logic/commands/AddNoteCommand.java [hunk 2]
```diff
@@ -77,9 +77,29 @@ public CommandResult execute(Model model) throws CommandException {
         model.setPerson(personToEdit, editedPerson);
         model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
 
+        Person person = FindCommand.getFoundPerson();
+        if (person != null && isNoteChanged(person, note)) {
+            model.updateFilteredPersonList(new IdentityCardNumberMatchesPredicate(person.getIdentityCardNumber()));
+            model.setDisplayNoteAsFirstFilteredPerson();
```
Comment (drustanyjt) [inline src/main/java/seedu/address/logic/commands/AddNoteCommand.java]: @jiahui0309 this also seems like a hackish way to try and get to the first person. It might be better to move the manipulation of the displayed note to person. Maybe `model` can have a method `setDisplayNoteAsPerson(Person)` that sets the display note to be the Person of our choice?

**Review by drustanyjt — COMMENTED** [review]
I think while this works, it would make iterating on the code quite difficult in the future. **I'm okay with approving this for now to add functionality _if_ we open another issue to remind ourselves to refactor this in the future. I'm also okay if we try to think of a better design first before merging this PR.**

I think one cleaner way would be to make the UI rely directly on a Note object, and whenever the contents of the Note object changes, the UI is also updated. This would require digging deeper into the codebase to find out how exactly JavaFX deals with modified objects.

File: src/main/java/seedu/address/logic/commands/AddNoteCommand.java (hunk 2 above)
Comment (jiahui0309) [reply src/main/java/seedu/address/logic/commands/AddNoteCommand.java]: I agree with you, I felt that this was a shortcut to obtain the required UI. I will take your input into consideration and try it out a bit more!

**Comment by drustanyjt** [comment]
Updated this PR with refactors to how displayed person is tracked, and also added in Show Command which closes #102.

Here's a brief demonstration of the show command. (Also showing the auto update of addnote)


https://github.com/AY2324S2-CS2103T-F14-2/tp/assets/110999129/a32bd60e-df2c-4ded-91e0-5a104e88d730

Summary of updates:

- Moved the tracking of Person from Find command to Model to enable updating of note
- Added Show Command
- Added Test Cases for Show

File: src/main/java/seedu/address/logic/commands/ShowCommand.java [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+ */
+public class ShowCommand extends Command {
+
+    public static final String COMMAND_WORD = "show";
+    public static final String MESSAGE_SHOW_NOTE_SUCCESS = "Displayed note of person: %1$s";
+
+    public static final String MESSAGE_CLEAR_NOTE_SUCCESS = "Note cleared.";
+
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Shows the note of the person whose IC matches the "
+            + "specified IC (case-insensitive) and displays it.\n"
```
Comment (Jayne1010) [inline src/main/java/seedu/address/logic/commands/ShowCommand.java]: do we not need to say valid ic number? cause I saw the change in every file

File: src/main/java/seedu/address/logic/commands/ShowCommand.java [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+            + "If no IC is given, the displayed note panel will be cleared. \n"
+            + "Parameters: IC (optional)\n"
+            + "Example (to display note): " + COMMAND_WORD + " t1234567A"
+            + "Example (to clear display): " + COMMAND_WORD;
```
Comment (Jayne1010) [inline src/main/java/seedu/address/logic/commands/ShowCommand.java:32]: is it ok if we make this into two different lines, cause two different instructions?

File: src/main/java/seedu/address/logic/commands/ShowCommand.java (hunk 3 above)
Comment (drustanyjt) [reply src/main/java/seedu/address/logic/commands/ShowCommand.java]: probably not too important, but I can add it in if you feel it's necessary

File: src/main/java/seedu/address/logic/commands/ShowCommand.java (hunk 4 above)
Comment (drustanyjt) [reply src/main/java/seedu/address/logic/commands/ShowCommand.java:32]: oh yes I missed that, will do

**Review by Jayne1010 — APPROVED** [review]
LGTM!
